### ISSUE TITLE
Capture ticket attachments into ticket data (operator uploads + pull Jira/GitHub logs inline, images stored)

### ISSUE THREAD

**Issue by alex-mooreslab** [navarrotech/Seraphim#291]
## Summary

Capture ticket attachments into Seraphim ticket data so the agent actually sees them. Two gaps:

1. **Internal tickets carry no attachments at all.** They are title + Markdown body only; an operator cannot attach a screenshot or a log file. For a UI bug the screenshots are the whole brief; for a crash/regression the log is the whole brief. Without them the agent is fixing blind.
2. **Source-ticket attachments are dropped on sync.** When a Jira (or GitHub) ticket is synced or hand-mirrored, its attachments do not come across. The agent only gets the description text. Today the workaround is the agent fetching them out-of-band via the authenticated Jira CLI, plus operators hand-mirroring Jira tickets as internal ones (see #290), which loses the images and any logs.

Hit in practice: the DebugAgent `BUG-*` Jira tickets are UI bugs whose screenshots live only on Jira; mirrored internal tickets had to instruct the agent to go fetch them by hand.

## Desired behavior

1. **Operator uploads on internal tickets.** Allow attaching images and files when creating/editing an internal ticket. Store the bytes as `bytea` (mirror the `task_screenshots` blob precedent: never returned in board/task JSON, streamed from a dedicated `GET` route, at-rest encryption assumed). Render them in the task view, and include them in the agent prompt.
2. **Pull source-ticket attachments into ticket data on sync/mirror.**
   - **Text/log attachments** (`.log`, `.txt`, `text/plain`, small `application/octet-stream` logs): inline their content into the ticket data (body or a synthetic comment) so the agent reads them directly, with a size guard (head/tail + a truncation marker beyond a cap, e.g. 30-50 KB).
   - **Image/binary attachments**: download and store them as ticket attachments (reusing #1's storage), so the agent can view the screenshots without leaving Seraphim. If full storage is deferred, at minimum surface the attachment list with an authenticated fetch recipe.
3. **Prompt rendering.** `prompt::build` includes attachments in the brief: inline log text, and image attachments as openable refs (the existing `render_discussion` already keeps Markdown image links intact for GitHub comments; extend that to stored attachments and to inlined logs).

## Implementation notes

- Jira side: `GET /rest/api/3/issue/{KEY}?fields=attachment` lists `filename` / `mimeType` / `size` / `content` (the download URL); fetch `content` with the configured `jira_email:jira_api_token` basic auth (Cloud). The connection config already lives in `settings` (`jira_base_url`, `jira_email`, `jira_api_token`, `jira_deployment`).
- GitHub side: issue/comment Markdown already carries attachment links; the gap is image/binary fetch + storage, not discovery.
- Storage: follow `task_screenshots` (bytea, streamed via a dedicated route, metadata-only in JSON). A shared `task_attachments` table keyed by `task_id` works for both operator uploads and pulled source attachments (carry `source`: `operator` | `jira` | `github`).
- Size/safety: cap inlined log text; store (do not inline) large or binary attachments; respect at-rest disk encryption as with the other blobs/secrets.

## Acceptance criteria

- An operator can attach an image/file to an internal ticket; it shows in the task view and reaches the agent's prompt.
- Syncing/mirroring a Jira ticket with attachments brings them into the ticket data: log/text attachments inlined (size-capped), image attachments stored and viewable, with no manual Jira CLI fetch required.
- The agent's prompt includes attachment content (inlined logs + openable image refs) so a UI bug or a log-driven bug can be fixed from the ticket alone.
- Large attachments are stored, not inlined; bytes are never returned in board/task JSON.

## Notes

- Complements #290 (auto-pull and work Jira tickets): attachment capture should run as part of the Jira sync/work path.
- No em dashes in user-facing text. No co-author trailers. Branch off `develop`.
- Related code: `task_screenshots` (the blob/stream precedent), `orchestrator::upsert_jira_issue`, `prompt::build` / `render_discussion`, `http/tasks.rs` (`create` / a new attachments route), `src/jira/` (client, add an attachments fetch).

**Comment by navarrotech** [comment]
Issue #291 implemented and shipped as PR #296 (against `develop`).

**What it does:** Ticket attachments are now captured into task data so the agent can see them instead of working blind.

**Backend (mirrors the `task_screenshots` blob precedent):**
- New `task_attachments` table (migration 0046): shared table keyed by `task_id`, bytes as `bytea`, with `source` (operator/jira/github) and `external_id` for pulled files, deduped via a partial unique index. Bytes stay out of board/task JSON; metadata-only `TaskAttachment` rides in `TaskDetail`; `GET /attachments/:id` streams the bytes.
- Operator upload `POST /tasks/:id/attachments`: raw file body, no multipart dependency, 25 MB cap.
- Jira capture via `list_attachments` + `download_attachment`, driven by `capture_jira_attachments` on first sync and at work time (best-effort, deduped, oversized skipped).
- Prompt gains an `# Attachments` section: small text/logs inlined head/tail-capped (40 KB); images/binaries listed as `curl` refs.

**Frontend:** Task page shows attachments (thumbnails + download links) with an "Add files" control on internal tickets; create-issue form uploads files after creation.

**Verification:** `cargo fmt`/`clippy` clean (55 warnings = develop baseline, zero new — extracted a `build_fresh_prompt` helper to stay under the line limit), 165 backend tests pass (3 new). Frontend `check` 0/0 + build pass. Migration, dedup index, and metadata-only SELECT validated against fresh PG17.

**Notes:**
- Branch is off `develop` (pre-#290): first-sync Jira capture delivers value today; work-time capture + prompt inlining activate once #290 merges.
- Visual review skipped (Playwright browser not installed) — filed an environment suggestion plus a follow-up to also store GitHub image attachments.

**Comment by navarrotech** [comment]
The agent fixed CI on PR #296, which failed because CI builds the PR merged with the current `develop`. Since `develop` had advanced to include #290 (auto-work Jira tickets), a newly added test calling `prompt::build(...)` collided with this branch's 8-argument signature change, producing `error[E0061]: this function takes 8 arguments but 7 were supplied` and failing both the Clippy and Test jobs.

Actions taken:
- Diagnosed the failure as a semantic merge conflict (textually clean but non-compiling), not a bug in the original code.
- Merged `origin/develop` into the branch (using `git merge`, not rebase, per the working agreement), verifying the reconciled `prompt.rs` preserved both #290's Jira rendering and this PR's attachments parameter and refactor.
- Passed `&[]` as the 8th argument to the merged-in Jira test so the combined tree compiles.
- Verified against CI's commands: `cargo fmt --check` clean, clippy reports no errors (53 warnings = develop baseline), 170 backend tests pass, and frontend `check`/`build` pass; `yarn.lock` stayed clean.
- Committed and pushed the fix. No UI changed, so no new visual review was needed. Stopped without watching CI.
